export const UI_STRINGS = {
    CURRENCY_UNIT: "đ",
    SEARCH_PLACEHOLDER: "Tìm kiếm trà sữa...",
    NO_RESULTS: "Không tìm thấy trà sữa nào phù hợp với",
    ADD_TO_CART: "Thêm vào giỏ hàng",
    ADDING_TO_CART: "Đang thêm...",
    CUSTOMIZE_TITLE: "Tùy chỉnh đồ uống",
    SELECT_TOPPING: "Chọn topping",
    SWEETNESS_LEVEL: "Độ ngọt",
    ICE_LEVEL: "Lượng đá",
    SIZE: "Kích thước",
    NOTE_LABEL: "Ghi chú cho ly trà sữa",
    NOTE_PLACEHOLDER: "Ví dụ: Ít đường hơn, nhiều đá, không topping, thêm lá bạc hà...",
    NOTE_LIMIT: "/200 ký tự",
    ORIGINAL_PRICE: "Giá gốc:",
    SIZE_PRICE: "Kích thước:",
    TOPPING_PRICE: "Topping:",
    TOTAL_PRICE: "Tổng cộng:",
    SELECT: "Chọn",
    QUANTITY: "Số lượng:",
    LOADING: "Đang tải...",
};
